### ISSUE TITLE
Problem about PHP version requirements for this package

### ISSUE THREAD

**Issue by peter279k** [antidot-framework/container#6]
**Describe the bug**

**To Reproduce**

When looking at the `composer.json` file, we can find that this package requires `php-7.4` version at least.

But looking at the `.travis.yml` file, it seems that `php-7.1`, `php-7.2` and `php-7.3` versions will be tested.

I'm not sure what is minimum PHP version for this package.

It seems that the Travis CI has been dropped/disabled and I think this file should be removed :).

**Comment by peter279k** [comment]
After looking at the [Travis CI page](https://travis-ci.org/github/antidot-framework/container), it seems to be triggered on upcoming PRs.

I think the `.travis.yml` file should be fixed and drop from `php-7.1` to `php-7.3` version tests.

Letting `php-7.4` version test during Travis CI building.

**Comment by kpicaza** [comment]
@peter279k You are right, the minimum version of PHP should be 7.4, a PR will be welcome, else I will fix it in the next days. Thank you very much for collaborating;-D

**Comment by peter279k** [comment]
I'm going to help you to fix this issue and improve some stuffs :+1: 

Let me add related PR to resolve this issue :).
